language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
jobs:
  include:
    - stage: build_business
    - script:
      - cd $TRAVIS_BUILD_DIR/v01/business
      - docker-compose -f docker-compose.yml up -d --build
      - docker-compose -f docker-compose.yml ps
    - script:
      - cd $TRAVIS_BUILD_DIR/v01/enterprise
      - docker-compose -f docker-compose.yml up -d --build
      - docker-compose -f docker-compose.yml ps
    - stage: test
    - script:
      - bash ./.travis/linters.sh
      - python tests.py
    - stage: deploy
    - script:
      - cd $TRAVIS_BUILD_DIR/v01/business
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker images
      - docker push trydirect/bitrix24:business
      - docker push trydirect/bitrix24:enterprise
      -
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
-
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
